# --log-driver gelf --log-opt gelf-address=udp://localhost:12201

version: '2'

services:

    logstash:
        image: logstash:5-alpine
        restart: always
        command:
            - '-e'
            - |
                input {
                    gelf {
                    }
                    tcp {
                        port => 5000
                    }
                }
                output {
                    elasticsearch {
                        hosts => "elasticsearch:9200"
                    }
                }
        expose:
            - 12201/udp
            - 5000/tcp
        ports:
            - 12201:12201/udp
            - 5000:5000/tcp

    elasticsearch:
        image: elasticsearch:5-alpine
        restart: always

    kibana:
        image: kibana:5
        restart: always
        ports:
            - 5601:5601
